Repository atlp-rwanda/orcas-phantom-backend, pull requests merged in 2020-10, with the labels that each got.

#9 ft(bus-routes):implementing bus CRUD operations
  .sequelizerc
  .travis.yml
  package-lock.json
  package.json
  src/controllers/busControllers.js
  src/database/config/config.js
  src/database/migrations/20200930142502-create-bus.js
  src/database/models/bus.js
  src/database/models/index.js
  src/database/seeders/20200930162517-Bus.js
  src/helper/bus.inputs.js
  src/index.js
  src/middleware/bus.validation.js
  src/routes/busRoutes.js
  src/test/bus.test.js
Labels: Ready to be merged

#11 Ft busstop crud
  package-lock.json
  package.json
  src/controllers/busStop.controllers.js
  src/database/migrations/20201001230119-create-bus-stop.js
  src/database/migrations/20201007152926-create-bus-stop.js
  src/database/models/busstop.js
  src/database/seeders/20201001232540-busStops.js
  src/database/seeders/20201007154101-BusStop.js
  src/helper/busStop.input.js
  src/index.js
  src/middleware/busStop.validation.js
  src/routes/busStop.route.js
  src/test/busStop.test.js
  src/test/main.test.js
Labels: Ready for reviews, Ready to be merged

#13 crud operations for users
  package-lock.json
  package.json
  src/controllers/bus.controllers.js
  src/controllers/routes.controller.js
  src/controllers/users.controller.js
  src/database/migrations/20201004214931-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/helper/hashedPassword.js
  src/helper/user.input.js
  src/index.js
  src/middleware/route.validation.js
  src/middleware/user.validation.js
  src/routes/bus.route.js
  src/routes/routes.route.js
  src/routes/users.route.js
  src/test/users.test.js
Labels: Ready to be merged

#15 user authentication
  package-lock.json
  package.json
  src/controllers/users.controller.js
  src/database/seeders/20200930162517-Bus.js
  src/database/seeders/20201001232540-busStops.js
  src/database/seeders/20201007154101-BusStop.js
  src/database/seeders/20201014060743-user.js
  src/helper/generateAuthToken.js
  src/helper/user.input.js
  src/middleware/user.validation.js
  src/middleware/verifyAuthToken.js
  src/routes/users.route.js
  src/test/users.test.js
Labels: Ready for reviews

#18 ft(docker):configuring docker
  .dockerignore
  Dockerfile
  docker-compose.yml
  src/database/models/index.js
Labels: Ready for reviews

#19 Authorization of all routes
  package.json
  src/controllers/users.controller.js
  src/middleware/verifyAuthToken.js
  src/routes/bus.route.js
  src/routes/busStop.route.js
  src/routes/routes.route.js
  src/routes/users.route.js
  src/test/bus.test.js
  src/test/busStop.test.js
  src/test/main.test.js
  src/test/route.test.js
  src/test/users.test.js
Labels: Ready to be merged
