Repository atlp-rwanda/orcas-phantom-backend, pull requests merged in 2020-11, with the labels that each got.

#26 ft(websocket):implementing websocket to unable real time update of Lo…
  package.json
  src/index.js
  src/server.js
  src/websocket-server.js
Labels: Ready to be merged

#27 fx(coveralls):fixing bug for updating coveralls
  .coveralls.yml
  README.md
  src/test/bus.test.js
Labels: Ready to be merged

#30 update swagger documentation file
  package.json
  src/controllers/users.controller.js
  src/helper/generateAuthToken.js
  src/helper/user.input.js
  src/index.js
  src/middleware/user.validation.js
  src/middleware/verifyAuthToken.js
  src/routes/users.route.js
  src/test/bus.test.js
  src/test/busStop.test.js
  src/test/route.test.js
  src/test/users.test.js
  swagger.json
Labels: Ready for reviews

#34 ch: get all bus stops in geojson format
  README.md
  package.json
  src/controllers/busStop.controllers.js
  src/routes/busStop.route.js
  src/test/busStop.test.js
  src/test/users.test.js
  swagger.json
Labels: Ready for reviews

#33 Adding busstops search functionality endpoint
  src/controllers/busStop.controllers.js
  src/controllers/users.controller.js
  src/index.js
  src/routes/busStop.route.js
  src/test/busStop.test.js
Labels: Ready to be merged

#37 fixed issue with retrieving user id
  package.json
  src/controllers/users.controller.js
Labels: Bug fix, Ready for reviews
